language: go

os:
  - windows
go:
  - "1.x"

notifications:
  irc:
    if: repo = namecoin/ctlpop
    channels:
      - "irc.oftc.net#namecoin-dev"
    on_success: never

stages:
  - test

# 'test' stage
script:
  - bash testdata/travis.bash
